### PR TITLE
Feat: Added Define Test API and Expose "Get App.vi" in Get [Poly].vi

### PR DESCRIPTION
**Pull request by kavin1730**
Feat: Add Define Test API and Expose "Get App.vi" in Get [Poly].vi

### CODE REVIEW

**Comment by kavin1730** [comment]
refactor: updated the Drona examples and added bin3 files to display examples in LV Example Finder

Pull Request was updated along with this commit.

**Comment by kavin1730** [comment]
Reverted the "update in example" (previous commit) to add it with different pull request

**Review by Sudarshan-Rajkumar — APPROVED** [review]

**Comment by kavin1730** [comment]
refactor: build package spec is updated with Define test API and Get App API

**Review by Sairam0496 — APPROVED** [review]
Reviewed
- standards okay
- new VI okay
- poly VI change okay
- palette change okay

**Pull request merged**
