### PR TITLE
refactor: Updated the Drona examples and added bin3 files to display examples in LV Example Finder

### PR DESCRIPTION
**Pull request by kavin1730**
* Drona.ini file is removed from library and added in project
* In calculator example shift registers in for loop is replaced with indexed tunnels. So that, even if any one of the test fails, it continues to check further tests.
* To list examples in LV Example Finder, bin3 file is added for individual examples
* Build spec is updated with these above changes

### CODE REVIEW

**Comment by Sairam0496** [comment]
- [x] INI file changes okay

**Review by Sairam0496 — CHANGES_REQUESTED** [review]
### **INI File linking** #44 
- Drona INI files are proper - now seeing an issue with SimpleCalcutor.ini (solution's INI files)
- We can create virtual folders and add the code, tests and the ini files can be added appropriately.
image

### **Examples Refactor** #46 
error from the loop might affect Close Stimulus - to be handled
image

### Example Finder #43 
basic looks okay - but can we try to add these examples to browse path of _"Toolkits and Modules>>Third-Party Add-Ons>>Other"_

### NOTE:
**While final commit, update the package version to 0.2.1**

**Comment by kavin1730** [comment]
[like]  Kavin Palanisamy reacted to your message:
________________________________

**Comment by kavin1730** [comment]
[0]     Kavin Palanisamy reacted to your message:
________________________________

**Pull request closed without merging**
